"""RFC 9457 problem-details error model (SPEC.md §8 API conventions)."""

from pydantic import BaseModel, ConfigDict, Field


class ProblemDetails(BaseModel):
    """A machine-readable error, per RFC 9457 (obsoletes RFC 7807).

    Deviates from the package's usual `extra="forbid"` (see `_base.SchemaModel`)
    by design: RFC 9457 defines problem types as extensible with additional
    members beyond `type`/`title`/`status`/`detail`/`instance`, and Steward's
    API surface uses that — e.g. a `budget_exceeded` problem carries the
    `RunBudget` that was exceeded as an extension member. Still frozen:
    an error value is a fact about what happened, not something to mutate.
    """

    model_config = ConfigDict(frozen=True, extra="allow")

    type: str = "about:blank"
    """URI reference identifying the problem type; "about:blank" means the
    problem has no more specific semantics than the HTTP status code."""

    title: str
    """Short, human-readable summary of the problem type."""

    status: int = Field(ge=100, le=599)
    """HTTP status code generated by the origin server for this occurrence."""

    detail: str | None = None
    """Human-readable explanation specific to this occurrence."""

    instance: str | None = None
    """URI reference identifying the specific occurrence of the problem."""
